// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ClearController from "./clear_controller"
application.register("clear", ClearController)

import CharacterCounter from "@stimulus-components/character-counter"
application.register("character-counter", CharacterCounter)

import Notification from "@stimulus-components/notification"
application.register("notification", Notification)
