// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// IMPORT JAVASCRIPT CONTROLLERS
import ScrollController from "./scroll_controller"
import ClearController from "./clear_controller"

application.register("scroll", ScrollController)
application.register("clear", ClearController)

// STIMULUS COMPONENTS
import CharacterCounter from "@stimulus-components/character-counter"
import Notification from "@stimulus-components/notification"
import Clipboard from '@stimulus-components/clipboard'

application.register("character-counter", CharacterCounter)
application.register("notification", Notification)
application.register('clipboard', Clipboard)
